name: CI - Test & Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.6'
          channel: stable

      - name: Install Lefthook
        run: npm install -g @evilmartians/lefthook

      - name: Install Flutter Dependencies
        run: flutter pub get

      - name: Run Lefthook
        run: lefthook run pre-commit --all-files

  test:
    name: Test
    needs: [code-quality]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Set Up Java
        uses: actions/setup-java@v5
        with:
          distribution: oracle
          java-version: '17'

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.6'
          channel: stable

      - name: Install Dependencies
        run: flutter pub get

      - name: Run Tests
        run: flutter test

  integration-test:
    name: Integration Tests (Android)
    needs: [code-quality]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.6'
          channel: stable

      - name: Set Up Java
        uses: actions/setup-java@v5
        with:
          distribution: oracle
          java-version: '17'

      - name: Install Flutter Dependencies
        run: flutter pub get

      - name: Run Integration Tests on Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 34
          arch: x86_64
          profile: pixel_7
          script: flutter test integration_test -d emulator-5554

  # build:
  #   name: Debug Build
  #   needs: [test, integration-test]
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v6

  #     - name: Set Up Java
  #       uses: actions/setup-java@v5
  #       with:
  #         distribution: oracle
  #         java-version: '17'

  #     - name: Set Up Flutter
  #       uses: subosito/flutter-action@v2
  #       with:
  #         flutter-version: '3.41.6'
  #         channel: stable

  #     - name: Install Dependencies
  #       run: flutter pub get

  #     - name: Build APK
  #       run: flutter build apk --debug

  #     - name: Build App Bundle
  #       run: flutter build appbundle --debug

  #     - name: Upload Artifacts
  #       uses: actions/upload-artifact@v7
  #       with:
  #         name: flutter-builds
  #         path: |
  #           build/app/outputs/flutter-apk/app-debug.apk
  #           build/app/outputs/bundle/debug/app-debug.aab
